version: '3'
services:
    rabbitmq:
       container_name: "myapp_rabbitmq"
       tty: true
       image: rabbitmq:3.6.1-management
       ports:
         - 15672:15672
         - 15671:15671
         - 5672:5672
       volumes:
         - /rabbitmq/lib:/var/lib/rabbitmq
         - /rabbitmq/log:/var/log/rabbitmq
         - /rabbitmq/conf:/etc/rabbitmq/
       healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000"]
            interval: 30s
            timeout: 10s
            retries: 5
    
    
    mongo:
        image: "mongo:latest"
        ports:
           - 27017:27017
      
    server:
       container_name: "game"
       build:
         context: .
         dockerfile: Dockerfile
       links:
         - rabbitmq
       restart: on-failure
       depends_on:
         - rabbitmq
         - mongo